[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Redirect admin to the CMS
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
