[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/static/blog.html"
  status = 200
