[build]
  publish = "."
  functions = "netlify/functions"
  
[functions]
  included_files = ["content/**"]  # <-- Add this

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/static/blog.html"
  status = 200

# Add these two new rules:
[[redirects]]
  from = "/netlify/functions/posts.js"
  to = "/.netlify/functions/posts"
  status = 200

[[redirects]]
  from = "/.netlify/functions/posts"
  to = "netlify/functions/posts.js"
  status = 200
