[build]
  publish = "."

[[redirects]]
  from = "/blog/:slug"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/posts/:slug"
  to = "/blog.html"
  status = 200

# Admin access
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
