backend:
  name: git-gateway
  branch: main

media_folder: "blog/images"
public_folder: "/blog/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Content", widget: "markdown" }
