backend:
  name: git-gateway
  branch: main

media_folder: "static/images" # Changed this
public_folder: "/images"      # And this

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"     # More specific path
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "URL Slug", widget: "string", pattern: ["^[a-z0-9-]+$", "Lowercase letters, numbers, and hyphens only"] }
      - { name: "date", label: "Publish Date", widget: "datetime" }
      - { name: "excerpt", label: "Short Excerpt", widget: "text" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Content", widget: "markdown" }
